[profile.default]
  evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  out = "out"
  script = "script"
  src = "src"
  test = "test"
  ast = true
  build_info = true



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
